# Generated by Django 2.2.6 on 2020-01-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='登陆标题')),
                ('mainTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='系统标题')),
                ('headTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='浏览器标题')),
                ('copyright', models.CharField(blank=True, max_length=100, null=True, verbose_name='底部版权信息')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统URL地址')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
