# Generated by Django 2.2.6 on 2020-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailHost', models.CharField(max_length=30, verbose_name='SMTP服务器')),
                ('emailPort', models.IntegerField(verbose_name='SMTP端口')),
                ('emailUser', models.EmailField(max_length=100, verbose_name='邮箱帐号')),
                ('emailPasswd', models.CharField(max_length=30, verbose_name='邮箱密码')),
            ],
            options={
                'verbose_name': '发件邮箱设置',
                'verbose_name_plural': '发件邮箱设置',
            },
        ),
    ]
