# Generated by Django 2.2.6 on 2020-02-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_emailsetup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsetup',
            old_name='emailPasswd',
            new_name='emailPassword',
        ),
    ]
