# Generated by Django 2.2.6 on 2020-02-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_remove_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Menu'),
        ),
    ]
