# Generated by Django 2.2.6 on 2020-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsensors',
            old_name='title',
            new_name='s_title',
        ),
        migrations.RemoveField(
            model_name='itemsensors',
            name='number',
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='modal',
            field=models.SmallIntegerField(choices=[(1, '振动监测'), (2, '油液监测')], default=1, verbose_name='采集器类型'),
        ),
    ]
