# Generated by Django 2.2.6 on 2020-03-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0003_auto_20200317_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsensors',
            name='s_title',
            field=models.CharField(max_length=128, null=True, verbose_name='传感器编号'),
        ),
    ]
