# Generated by Django 2.2.6 on 2020-03-23 15:53

import PMsys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0006_auto_20200323_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsfiles',
            name='file',
            field=models.FileField(unique=True, upload_to=PMsys.models.upload_path, verbose_name='文件位置'),
        ),
    ]
