# Generated by Django 2.2.6 on 2020-04-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0008_auto_20200402_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemstay',
            old_name='hosteladdress',
            new_name='hoteladdress',
        ),
    ]
