# Generated by Django 2.2.6 on 2020-04-04 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PMsys', '0009_auto_20200402_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtrip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='填写人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemstay',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注说明'),
        ),
    ]
