# Generated by Django 2.2.6 on 2020-04-07 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PMsys', '0010_auto_20200404_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemgoods',
            old_name='operator',
            new_name='user',
        ),
        migrations.AddField(
            model_name='itemgoods',
            name='memo',
            field=models.TextField(default=1, verbose_name='发货说明'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemExplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('type', models.SmallIntegerField(choices=[(1, '工具借用'), (2, '其它')], verbose_name='文件类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMsys.Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '工具借用',
                'verbose_name_plural': '工具借用',
            },
        ),
    ]
