# Generated by Django 2.2.6 on 2020-04-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0011_auto_20200407_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemgoods',
            old_name='item',
            new_name='items',
        ),
    ]
