# Generated by Django 2.2.6 on 2020-04-21 02:14

import PMsys.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0012_auto_20200408_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemexecutr',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='施工人员状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgoods',
            name='type',
            field=models.SmallIntegerField(default=1, verbose_name='类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to=PMsys.models.upload_path_image, verbose_name='发货图片'),
        ),
        migrations.AlterField(
            model_name='itemexecutr',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='施工人员'),
        ),
    ]
