# Generated by Django 2.2.6 on 2020-04-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMsys', '0014_auto_20200423_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemserver',
            name='disk_unit',
            field=models.SmallIntegerField(default=1, verbose_name='硬盘单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemserver',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='items',
            name='x',
            field=models.FloatField(default=1, verbose_name='坐标x'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='y',
            field=models.FloatField(default=1, verbose_name='坐标y'),
            preserve_default=False,
        ),
    ]
